//! High-speed structured prompt router and classifier.
//!
//! Evaluates incoming user prompts to extract task categories, target programming languages,
//! estimated complexity scores (1..=10), reasoning requirements, and dynamic ensemble sizing
//! using a sub-30ms barrier with instant heuristic fallback (<2ms).

use serde::{Deserialize, Serialize};
use std::time::Instant;

/// Routing decision payload generated by the structured router or heuristic fallback.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct RoutingDecision {
    pub task_category: String,
    pub target_language: Option<String>,
    pub complexity_score: u8, // 1..=10
    pub ensemble_size: usize,
    pub requires_reasoning: bool,
    pub suggested_models: Vec<String>,
    pub routed_by: String, // "qwen2.5-coder:0.5b", "heuristic_fallback", etc.
    pub routing_duration_ms: u64,
}

/// Router that attempts sub-30ms Ollama classification and falls back instantly to heuristics.
#[derive(Debug, Clone)]
pub struct StructuredRouter {
    pub endpoint: String,
    pub model_tag: String,
    pub timeout_ms: u64,
}

impl Default for StructuredRouter {
    fn default() -> Self {
        let endpoint = std::env::var("LOCAL_OLLAMA_ENDPOINT")
            .unwrap_or_else(|_| "http://127.0.0.1:11434".to_string());
        Self {
            endpoint,
            model_tag: "qwen2.5-coder:0.5b".to_string(),
            timeout_ms: 30,
        }
    }
}

impl StructuredRouter {
    pub fn new(
        endpoint: impl Into<String>,
        model_tag: impl Into<String>,
        timeout_ms: u64,
    ) -> Self {
        Self {
            endpoint: endpoint.into(),
            model_tag: model_tag.into(),
            timeout_ms,
        }
    }

    /// Routes the prompt by querying the fast local router model or falling back to heuristics.
    pub fn route_prompt(
        &self,
        prompt: &str,
        free_ram_gb: f64,
        free_vram_mb: u64,
    ) -> RoutingDecision {
        let start = Instant::now();

        // If timeout_ms is 0 or Ollama is disabled, bypass network probe immediately
        if self.timeout_ms > 0 && std::env::var("MODELFUSION_DISABLE_OLLAMA_ROUTER").is_err() {
            if let Some(mut decision) = self.try_ollama_route(prompt, free_ram_gb, free_vram_mb) {
                decision.routing_duration_ms = start.elapsed().as_millis() as u64;
                return decision;
            }
        }

        let mut fallback = self.heuristic_fallback(prompt, free_ram_gb, free_vram_mb);
        fallback.routing_duration_ms = start.elapsed().as_millis() as u64;
        fallback
    }

    /// Attempts to query the local router LLM (e.g. Qwen2.5-Coder:0.5b) within the timeout window.
    fn try_ollama_route(
        &self,
        prompt: &str,
        free_ram_gb: f64,
        free_vram_mb: u64,
    ) -> Option<RoutingDecision> {
        let client = reqwest::blocking::Client::builder()
            .timeout(std::time::Duration::from_millis(self.timeout_ms))
            .build()
            .ok()?;

        let url = format!("{}/api/generate", self.endpoint.trim_end_matches('/'));

        // Short classification prompt designed for immediate JSON completion
        let system_prompt = "You are a fast code classifier. Return JSON only with fields: task_category (string), target_language (string or null), complexity_score (int 1-10), requires_reasoning (bool).";
        let user_query = if prompt.len() > 300 {
            &prompt[..300]
        } else {
            prompt
        };

        let request_body = serde_json::json!({
            "model": self.model_tag,
            "prompt": format!("{}\nUser Request: {}", system_prompt, user_query),
            "format": "json",
            "stream": false,
            "options": {
                "num_predict": 48,
                "temperature": 0.0
            }
        });

        let resp = client.post(&url).json(&request_body).send().ok()?;
        if !resp.status().is_success() {
            return None;
        }

        let json_resp: serde_json::Value = resp.json().ok()?;
        let response_text = json_resp.get("response")?.as_str()?;
        let parsed: serde_json::Value = serde_json::from_str(response_text).ok()?;

        let task_category = parsed
            .get("task_category")
            .and_then(|v| v.as_str())
            .unwrap_or("code-generation")
            .to_string();

        let target_language = parsed
            .get("target_language")
            .and_then(|v| v.as_str())
            .map(|s| s.to_lowercase());

        let raw_complexity = parsed
            .get("complexity_score")
            .and_then(|v| v.as_u64())
            .unwrap_or(5);
        let complexity_score = raw_complexity.clamp(1, 10) as u8;

        let requires_reasoning = parsed
            .get("requires_reasoning")
            .and_then(|v| v.as_bool())
            .unwrap_or_else(|| complexity_score >= 6);

        let (ensemble_size, suggested_models) = Self::compute_ensemble_and_models(
            complexity_score,
            requires_reasoning,
            free_ram_gb,
            free_vram_mb,
        );

        Some(RoutingDecision {
            task_category,
            target_language,
            complexity_score,
            ensemble_size,
            requires_reasoning,
            suggested_models,
            routed_by: self.model_tag.clone(),
            routing_duration_ms: 0,
        })
    }

    /// Instant heuristic classification (<2ms) extracting programming language, task type,
    /// complexity, and sizing ensemble based on runtime available RAM/VRAM.
    pub fn heuristic_fallback(
        &self,
        prompt: &str,
        free_ram_gb: f64,
        free_vram_mb: u64,
    ) -> RoutingDecision {
        let start = Instant::now();
        let target_language = Self::detect_target_language(prompt);
        let (task_category, keyword_complexity) = Self::detect_task_category(prompt, target_language.is_some());
        let complexity_score = Self::calculate_complexity(prompt, keyword_complexity);
        let requires_reasoning = Self::detect_reasoning_need(prompt, complexity_score);

        let (ensemble_size, suggested_models) = Self::compute_ensemble_and_models(
            complexity_score,
            requires_reasoning,
            free_ram_gb,
            free_vram_mb,
        );

        let duration_ms = start.elapsed().as_millis() as u64;

        RoutingDecision {
            task_category,
            target_language,
            complexity_score,
            ensemble_size,
            requires_reasoning,
            suggested_models,
            routed_by: "heuristic_fallback".to_string(),
            routing_duration_ms: duration_ms,
        }
    }

    /// Detects programming language from file extensions, syntax keywords, or explicit names.
    pub fn detect_target_language(prompt: &str) -> Option<String> {
        let lower = prompt.to_lowercase();

        // 1. Explicit extension or token matches
        if lower.contains(".rs") || lower.contains("rust") || lower.contains("cargo") || lower.contains("fn main") {
            return Some("rust".to_string());
        }
        if lower.contains(".py") || lower.contains("python") || lower.contains("pytest") || lower.contains("def ") || lower.contains("import ") {
            return Some("python".to_string());
        }
        if lower.contains(".ts") || lower.contains("typescript") || lower.contains(".tsx") || lower.contains("interface ") {
            return Some("typescript".to_string());
        }
        if lower.contains(".js") || lower.contains("javascript") || lower.contains(".jsx") || lower.contains("console.log") {
            return Some("javascript".to_string());
        }
        if lower.contains(".go") || lower.contains("golang") || lower.contains("func ") || lower.contains("package main") {
            return Some("go".to_string());
        }
        if lower.contains(".cpp") || lower.contains("c++") || lower.contains(".hpp") || lower.contains("std::") || lower.contains("#include") {
            return Some("cpp".to_string());
        }
        if lower.contains(".cs") || lower.contains("csharp") || lower.contains("c#") || lower.contains("using system") {
            return Some("csharp".to_string());
        }
        if lower.contains(".java") || lower.contains("java") || lower.contains("public class") {
            return Some("java".to_string());
        }
        if lower.contains(".sql") || lower.contains("select ") && lower.contains(" from ") {
            return Some("sql".to_string());
        }
        if lower.contains(".sh") || lower.contains("bash") || lower.contains("shell") || lower.contains("powershell") || lower.contains(".ps1") {
            return Some("shell".to_string());
        }

        None
    }

    /// Detects task category and associated baseline complexity offset.
    fn detect_task_category(prompt: &str, has_code_lang: bool) -> (String, i16) {
        let lower = prompt.to_lowercase();

        if lower.contains("test") || lower.contains("assert") || lower.contains("mock") || lower.contains("unit test") || lower.contains("benchmark") {
            ("testing".to_string(), 1)
        } else if lower.contains("fix") || lower.contains("bug") || lower.contains("error") || lower.contains("panic") || lower.contains("exception") || lower.contains("crash") {
            ("bug-fix".to_string(), 2)
        } else if lower.contains("refactor") || lower.contains("clean up") || lower.contains("restructure") || lower.contains("optimize") || lower.contains("simplify") {
            ("refactoring".to_string(), 2)
        } else if lower.contains("architect") || lower.contains("design") || lower.contains("distributed") || lower.contains("system") || lower.contains("pipeline") {
            ("architecture".to_string(), 3)
        } else if lower.contains("security") || lower.contains("vulnerability") || lower.contains("cve") || lower.contains("audit") || lower.contains("sanitize") {
            ("security".to_string(), 3)
        } else if lower.contains("doc") || lower.contains("explain") || lower.contains("comment") || lower.contains("readme") {
            ("documentation".to_string(), -1)
        } else if has_code_lang || lower.contains("function") || lower.contains("class") || lower.contains("implement") || lower.contains("write") {
            ("code-generation".to_string(), 1)
        } else {
            ("general".to_string(), 0)
        }
    }

    /// Computes prompt complexity on a 1..=10 scale.
    fn calculate_complexity(prompt: &str, category_offset: i16) -> u8 {
        let lower = prompt.to_lowercase();
        let mut score: i16 = 3 + category_offset;

        // Prompt length factors
        if prompt.len() > 300 {
            score += 1;
        }
        if prompt.len() > 800 {
            score += 1;
        }
        if prompt.len() > 2000 {
            score += 2;
        }

        // Advanced systems keywords
        let high_complexity_keywords = [
            "deadlock", "race condition", "mutex", "concurrency", "async",
            "atomic", "memory leak", "oom", "ctypes", "win32", "kernel",
            "unsafe", "job object", "mcts", "reinforcement learning",
            "ast", "parser", "compiler", "simd", "zero-copy", "cache line",
        ];
        for kw in &high_complexity_keywords {
            if lower.contains(kw) {
                score += 1;
            }
        }

        // Low complexity keywords
        let low_complexity_keywords = [
            "hello", "hi", "what is", "quick question", "format", "simple",
            "explain in one sentence", "typo",
        ];
        for kw in &low_complexity_keywords {
            if lower.contains(kw) {
                score -= 2;
            }
        }

        score.clamp(1, 10) as u8
    }

    /// Evaluates whether the query necessitates deliberate multi-step reasoning.
    fn detect_reasoning_need(prompt: &str, complexity: u8) -> bool {
        if complexity >= 6 {
            return true;
        }

        let lower = prompt.to_lowercase();
        let reasoning_tokens = [
            "reason", "think", "why", "prove", "derive", "algorithm",
            "tradeoff", "analysis", "deepseek-r1", "investigate", "audit",
        ];

        reasoning_tokens.iter().any(|t| lower.contains(t))
    }

    /// Computes ensemble size and candidate model suggestions derived from
    /// runtime available memory and task demands.
    pub fn compute_ensemble_and_models(
        complexity: u8,
        requires_reasoning: bool,
        free_ram_gb: f64,
        free_vram_mb: u64,
    ) -> (usize, Vec<String>) {
        // Dynamic Hardware Sizing: Available Runtime Memory Rule
        // Matrix:
        // Tier 1: Available RAM >= 48 GB OR Free VRAM >= 24 GB (24,000 MB)
        // Tier 2: Available RAM >= 24 GB OR Free VRAM >= 14 GB (14,000 MB)
        // Tier 3: Available RAM >= 12 GB OR Free VRAM >= 4.5 GB (4,500 MB)
        // Tier 4: Available RAM >= 6 GB OR Free VRAM >= 2 GB (2,000 MB)
        // Tier 5: Available RAM < 6 GB

        let (max_hw_ensemble, model_pool) = if free_ram_gb >= 48.0 || free_vram_mb >= 24_000 {
            let pool = if requires_reasoning {
                vec![
                    "qwen2.5:32b".to_string(),
                    "deepseek-r1:32b".to_string(),
                    "deepseek-r1:14b".to_string(),
                    "qwen2.5-coder:32b".to_string(),
                    "qwen2.5:14b".to_string(),
                    "deepseek-r1:7b".to_string(),
                    "qwen2.5:7b".to_string(),
                ]
            } else {
                vec![
                    "qwen2.5:32b".to_string(),
                    "qwen2.5-coder:32b".to_string(),
                    "qwen2.5:14b".to_string(),
                    "qwen2.5-coder:14b".to_string(),
                    "qwen2.5:7b".to_string(),
                    "deepseek-r1:14b".to_string(),
                    "qwen2.5:3b".to_string(),
                ]
            };
            (7usize, pool)
        } else if free_ram_gb >= 24.0 || free_vram_mb >= 14_000 {
            let pool = if requires_reasoning {
                vec![
                    "qwen2.5:14b".to_string(),
                    "deepseek-r1:14b".to_string(),
                    "deepseek-r1:7b".to_string(),
                    "qwen2.5-coder:14b".to_string(),
                    "qwen2.5:7b".to_string(),
                ]
            } else {
                vec![
                    "qwen2.5:14b".to_string(),
                    "qwen2.5-coder:14b".to_string(),
                    "qwen2.5:7b".to_string(),
                    "qwen2.5-coder:7b".to_string(),
                    "deepseek-r1:7b".to_string(),
                ]
            };
            (5usize, pool)
        } else if free_ram_gb >= 12.0 || free_vram_mb >= 4_500 {
            let pool = if requires_reasoning {
                vec![
                    "qwen2.5:7b".to_string(),
                    "deepseek-r1:7b".to_string(),
                    "deepseek-r1:1.5b".to_string(),
                    "qwen2.5-coder:7b".to_string(),
                ]
            } else {
                vec![
                    "qwen2.5:7b".to_string(),
                    "qwen2.5-coder:7b".to_string(),
                    "qwen2.5:3b".to_string(),
                    "deepseek-r1:1.5b".to_string(),
                ]
            };
            (4usize, pool)
        } else if free_ram_gb >= 6.0 || free_vram_mb >= 2_000 {
            let pool = if requires_reasoning {
                vec![
                    "qwen2.5:3b".to_string(),
                    "deepseek-r1:1.5b".to_string(),
                    "qwen2.5:1.5b".to_string(),
                ]
            } else {
                vec![
                    "qwen2.5:3b".to_string(),
                    "qwen2.5-coder:3b".to_string(),
                    "qwen2.5:1.5b".to_string(),
                ]
            };
            (3usize, pool)
        } else {
            let pool = vec![
                "qwen2.5:1.5b".to_string(),
                "qwen2.5:0.5b".to_string(),
            ];
            (2usize, pool)
        };

        // Ensemble size scales with both hardware headroom and task complexity
        let target_size = if complexity <= 2 {
            1
        } else if complexity <= 4 {
            2.min(max_hw_ensemble)
        } else if complexity <= 6 {
            3.min(max_hw_ensemble)
        } else if complexity <= 8 {
            5.min(max_hw_ensemble)
        } else {
            max_hw_ensemble
        };

        let ensemble_size = target_size.clamp(1, model_pool.len());
        let suggested_models = model_pool.into_iter().take(ensemble_size).collect();

        (ensemble_size, suggested_models)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_heuristic_fallback_latency() {
        let router = StructuredRouter::default();
        let start = Instant::now();
        let decision = router.heuristic_fallback(
            "Fix the race condition and deadlock in the Win32 Job Object ctypes handler in Rust",
            32.0,
            16000,
        );
        let elapsed = start.elapsed();

        // Heuristic fallback MUST be sub-2ms
        assert!(elapsed.as_millis() < 5, "Heuristic fallback took too long: {:?}", elapsed);
        assert_eq!(decision.routed_by, "heuristic_fallback");
        assert_eq!(decision.target_language, Some("rust".to_string()));
        assert_eq!(decision.task_category, "bug-fix");
        assert!(decision.complexity_score >= 6);
        assert!(decision.requires_reasoning);
        assert!(!decision.suggested_models.is_empty());
    }

    #[test]
    fn test_language_detection() {
        assert_eq!(
            StructuredRouter::detect_target_language("write a python script with pytest"),
            Some("python".to_string())
        );
        assert_eq!(
            StructuredRouter::detect_target_language("create a new cargo package with fn main"),
            Some("rust".to_string())
        );
        assert_eq!(
            StructuredRouter::detect_target_language("interface UserProfile { name: string; }"),
            Some("typescript".to_string())
        );
        assert_eq!(
            StructuredRouter::detect_target_language("std::vector<int> nums; #include <iostream>"),
            Some("cpp".to_string())
        );
        assert_eq!(
            StructuredRouter::detect_target_language("package main func main() {}"),
            Some("go".to_string())
        );
        assert_eq!(
            StructuredRouter::detect_target_language("explain quantum computing"),
            None
        );
    }

    #[test]
    fn test_hardware_scaling_matrix() {
        // Tier 1: RAM >= 48GB or VRAM >= 24GB
        let (size1, models1) = StructuredRouter::compute_ensemble_and_models(9, true, 64.0, 24000);
        assert_eq!(size1, 7);
        assert!(models1.contains(&"qwen2.5:32b".to_string()));
        assert!(models1.contains(&"deepseek-r1:32b".to_string()));

        // Tier 2: RAM 32GB, VRAM 16GB
        let (size2, models2) = StructuredRouter::compute_ensemble_and_models(8, true, 32.0, 16000);
        assert_eq!(size2, 5);
        assert!(models2.contains(&"qwen2.5:14b".to_string()));

        // Tier 3: RAM 16GB, VRAM 6GB
        let (size3, models3) = StructuredRouter::compute_ensemble_and_models(6, false, 16.0, 6000);
        assert!(size3 <= 4);
        assert!(models3.contains(&"qwen2.5:7b".to_string()));

        // Tier 4: RAM 8GB, VRAM 3GB
        let (size4, models4) = StructuredRouter::compute_ensemble_and_models(5, false, 8.0, 3000);
        assert!(size4 <= 3);
        assert!(models4.contains(&"qwen2.5:3b".to_string()));

        // Tier 5: RAM 4GB, VRAM 0GB
        let (size5, models5) = StructuredRouter::compute_ensemble_and_models(2, false, 4.0, 0);
        assert!(size5 <= 2);
        assert!(models5.contains(&"qwen2.5:1.5b".to_string()));
    }

    #[test]
    fn test_json_serialization() {
        let decision = RoutingDecision {
            task_category: "refactoring".to_string(),
            target_language: Some("rust".to_string()),
            complexity_score: 7,
            ensemble_size: 4,
            requires_reasoning: true,
            suggested_models: vec!["qwen2.5:7b".to_string(), "deepseek-r1:7b".to_string()],
            routed_by: "heuristic_fallback".to_string(),
            routing_duration_ms: 1,
        };

        let json = serde_json::to_string(&decision).expect("Serialization failed");
        let deserialized: RoutingDecision = serde_json::from_str(&json).expect("Deserialization failed");
        assert_eq!(decision, deserialized);
    }
}
